spring.application.name=cashflow
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/cashflow
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


## Datas automáticas
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

api.security.token.secret=${JWT_SECRET}:my-secret-key}